# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from bs4 import BeautifulSoup
import os, hashlib, requests
class Ui_MainWindow(object):

    fileLoc= ""
    URL= ""
    sh256= ""

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(94, 94, 94)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.buttonpress("inp"))
        self.inputButton.setGeometry(QtCore.QRect(260, 90, 291, 111))
        self.inputButton.setStyleSheet("QPushButton\n"
"{\n"
"    border-radius: 55px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.381, stop:0 rgba(255, 88, 0, 255), stop:1 rgba(122, 79, 255, 255));\n"
"    \n"
"    font: 63 23pt \"Segoe UI Semibold\";\n"
"}\n"
"QPushButton:clicked\n"
"{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.557, x2:0, y2:0, stop:0 rgba(255, 88, 0, 255), stop:1 rgba(122, 79, 255, 255))\n"
"    \n"
"    font: 63 23pt \"Segoe UI Semibold\";\n"
"}")
        self.inputButton.setObjectName("inputButton")
        self.logOutput = QtWidgets.QLabel(self.centralwidget)
        self.logOutput.setGeometry(QtCore.QRect(40, 240, 501, 211))
        self.logOutput.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(85, 255, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 10pt \"Consolas\";\n"
"    border: 2px grey;\n"
"    border-radius: 5px;\n"
"}")
        self.logOutput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.logOutput.setObjectName("logOutput")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(560, 240, 71, 21))
        self.label.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(0, 0, 0, 0);\n"
"    color: rgb(85, 255, 0);\n"
"    font: 10pt \"Consolas\";\n"
"    border-radius: 20px;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 480, 801, 61))
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"    color: white;\n"
"    \n"
"    font: ;\n"
"    font: 75 italic 16pt \"Arial\";\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(560, 270, 211, 51))
        self.result.setStyleSheet("QLabel\n"
"{\n"
"     border-radius: 25px;   \n"
"     background-color: grey;\n"
"}")
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.sigmaScore = QtWidgets.QLabel(self.centralwidget)
        self.sigmaScore.setGeometry(QtCore.QRect(560, 330, 211, 121))
        self.sigmaScore.setStyleSheet("QLabel\n"
"{\n"
"     border-radius: 25px;   \n"
"     background-color: grey;\n"
"}")
        self.sigmaScore.setAlignment(QtCore.Qt.AlignCenter)
        self.sigmaScore.setObjectName("sigmaScore")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def buttonpress(self, pressed):
        response= str(QFileDialog.getOpenFileName(None,"Select File"))
        if response=="('', '')":
                self.logOutput.setText(self.logOutput.text()+"\n"+"No file chosen.")
        else:
                self.fileLoc= response[2:len(response)-19]
                self.logOutput.setText(self.logOutput.text()+"\n"+"File"+self.fileLoc+" is currently the chosen file.")
                self.hasher()
        print(response)
    def hasher(self):
        self.logOutput.setText(self.logOutput.text()+"\n"+"Hashing using SHA256...")
        self.fileLoc
        with open(self.fileLoc,"rb") as f:
                f_byte= f.read()
                result= hashlib.sha256(f_byte)
                self.sh256=result.hexdigest()
                self.logOutput.setText(self.logOutput.text()+"\n"+self.sh256)
                self.vtcontact()
    def vtcontact(self):
        self.logOutput.setText(self.logOutput.text()+"\n"+"Contacting VirusTotal.")
        self.result.setText("Processing...")
        print(self.sh256)
        self.URL= "http://virustotal.com/gui/file/"+self.sh256+"/details"
        page= requests.get(self.URL)
        content= page.content
        soup= BeautifulSoup(content, 'html.parser')
        print(page.content)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inputButton.setText(_translate("MainWindow", "Select input file"))
        self.logOutput.setText(_translate("MainWindow", "Log:"))
        self.label.setText(_translate("MainWindow", "Result:"))
        self.label_3.setText(_translate("MainWindow", "SigmaAV | Alpha Phase"))
        self.result.setText(_translate("MainWindow", "No file chosen."))
        self.sigmaScore.setText(_translate("MainWindow", "SigmaScore: -"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
