# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(94, 94, 94)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 90, 291, 111))
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    border-radius: 55px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.381, stop:0 rgba(255, 88, 0, 255), stop:1 rgba(122, 79, 255, 255));\n"
"    \n"
"    font: 63 23pt \"Segoe UI Semibold\";\n"
"}\n"
"QPushButton:clicked\n"
"{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.557, x2:0, y2:0, stop:0 rgba(255, 88, 0, 255), stop:1 rgba(122, 79, 255, 255))\n"
"    \n"
"    font: 63 23pt \"Segoe UI Semibold\";\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 240, 501, 211))
        self.label.setStyleSheet("QLabel\n"
"{\n"
"    color: rgb(85, 255, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 10pt \"Consolas\";\n"
"    border: 2px grey;\n"
"    border-radius: 5px;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(560, 240, 71, 21))
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"    background-color: rgb(0, 0, 0, 0);\n"
"    color: rgb(85, 255, 0);\n"
"    font: 10pt \"Consolas\";\n"
"    border-radius: 20px;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 480, 801, 61))
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"    color: white;\n"
"    \n"
"    font: ;\n"
"    font: 75 italic 16pt \"Arial\";\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(560, 270, 211, 51))
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"     border-radius: 25px;   \n"
"     background-color: grey;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(560, 330, 211, 121))
        self.label_5.setStyleSheet("QLabel\n"
"{\n"
"     border-radius: 25px;   \n"
"     background-color: grey;\n"
"}")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Select input file"))
        self.label.setText(_translate("MainWindow", "Log:"))
        self.label_2.setText(_translate("MainWindow", "Result:"))
        self.label_3.setText(_translate("MainWindow", "SigmaAV | Alpha Phase"))
        self.label_4.setText(_translate("MainWindow", "No file chosen."))
        self.label_5.setText(_translate("MainWindow", "SigmaScore: -"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
